name: Update Experience in README

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python update_readme.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "mowne67"
          git config --global user.email "mowne67@github.com"
          git add README.md
          git commit -m "Update experience in README" || echo "No changes to commit"
          git push
